# Generated by Django 4.2.13 on 2024-05-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('manager', 'Manager'), ('admin', 'Admin'), ('customer', 'Customer'), ('owner', 'Owner'), ('director', 'Director'), ('supplier', 'Supplier')], default='staff', max_length=50, null=True, verbose_name='Роль в компании'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Специальность'),
        ),
    ]
