# Generated by Django 4.2.13 on 2024-05-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0002_alter_workspace_address'),
        ('user', '0002_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='workspaces',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='work_space.workspace', verbose_name='Место работы'),
        ),
    ]
