# Generated by Django 4.2.13 on 2024-05-20 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type_workspace', models.CharField(choices=[('service', 'Service'), ('store', 'Store'), ('office', 'Office'), ('warehouse', 'Warehouse')], default='service', max_length=50)),
                ('opening_date', models.DateField(auto_now_add=True, verbose_name='Дата открытия точки')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WorkSpace',
                'verbose_name_plural': 'WorkSpaces',
            },
        ),
    ]
